function norm(s) {
  return String(s || '')
    .trim()
    .toLowerCase()
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/\s+/g, ' ')
    .replace(/[؟?!.…]+$/g, '')
    .replace(/\s*[،,:;]+\s*$/g, '');
}

// TR <-> ID sık kullanılan tanışma cümleleri / soruları.
// Not: Eşleştirme "exact-ish" (normalize edilmiş metin). Metin tam tutarsa Gemini/DeepL çağrısı yapılmaz.
const PAIRS = [
  ['Merhaba', 'Halo'],
  ['Selam', 'Hai'],
  ['Nasılsın', 'Apa kabar'],
  ['Sen nasılsın', 'Kamu apa kabar'],
  ['İyiyim', 'Aku baik'],
  ['İyiyim teşekkürler', 'Aku baik, terima kasih'],
  ['İyiyim, sen nasılsın', 'Aku baik, kamu bagaimana'],
  ['Evet', 'Iya'],
  ['Hayır', 'Tidak'],
  ['Tamam', 'Oke'],
  ['Okey', 'Oke'],
  ['OK', 'Oke'],
  ['Olur', 'Boleh'],
  ['Olmaz', 'Tidak bisa'],
  ['Bilmiyorum', 'Aku tidak tahu'],
  ['Belki', 'Mungkin'],
  ['İyi', 'Baik'],
  ['Güzel', 'Bagus'],
  ['Severim', 'Aku suka'],
  ['Sevmem', 'Aku tidak suka'],
  ['Adın ne', 'Siapa namamu'],
  ['Benim adım', 'Namaku'],
  ['Kaç yaşındasın', 'Berapa usiamu'],
  ['Kaç', 'Berapa'],
  ['Kim', 'Siapa'],
  ['Ne zaman', 'Kapan'],
  ['Nerede', 'Di mana'],
  ['Nasıl', 'Bagaimana'],
  ['Ne kadar', 'Berapa'],
  ['Nerelisin', 'Kamu asal dari mana'],
  ['Nerede yaşıyorsun', 'Kamu tinggal di mana'],
  ['Hangi şehirde yaşıyorsun', 'Kamu tinggal di kota mana'],
  ['Şu an hangi şehirde yaşıyorsun', 'Sekarang kamu tinggal di kota mana'],
  ['Mesleğin ne', 'Apa pekerjaanmu'],
  ['Ne iş yapıyorsun', 'Kamu kerja apa'],
  ['Yabancı dil biliyor musun', 'Apakah kamu bisa bahasa asing'],
  ['Okuyor musun', 'Apakah kamu masih kuliah'],
  ['Hobilerin neler', 'Apa hobimu'],
  ['Boş zamanlarında ne yaparsın', 'Apa yang kamu lakukan di waktu luang'],
  ['Ailen nasıl', 'Bagaimana keluargamu'],
  ['Kaç kardeşsiniz', 'Kamu punya berapa saudara'],
  ['Anne ve baban ne iş yapıyor', 'Apa pekerjaan ayah dan ibumu'],
  ['Daha önce evlendin mi', 'Apakah kamu pernah menikah sebelumnya'],
  ['Ne zaman boşandın', 'Kapan kamu bercerai'],
  ['Neden boşandın', 'Kenapa kamu bercerai'],
  ['Çocuğun var mı', 'Apakah kamu punya anak'],
  ['Kaç çocuğun var', 'Kamu punya berapa anak'],
  ['Çocukların kaç yaşında', 'Anakmu umur berapa'],
  ['Çocuklar kiminle yaşıyor', 'Anak-anak tinggal dengan siapa'],
  ['Ailenle mi yaşıyorsun', 'Apakah kamu tinggal dengan keluargamu'],
  ['Yalnız mı yaşıyorsun', 'Apakah kamu tinggal sendiri'],
  ['Evlilikten beklentin nedir', 'Apa harapanmu dari pernikahan'],
  ['Ciddi bir ilişki istiyorum', 'Aku ingin hubungan yang serius'],
  ['Evliliğe hazır mısın', 'Apakah kamu siap untuk menikah'],
  ['Ne zaman evlenmek istiyorsun', 'Kapan kamu ingin menikah'],
  ['Evlilikte senin için en önemli şey nedir', 'Apa hal terpenting bagimu dalam pernikahan'],
  ['Dindar mısın', 'Apakah kamu religius'],
  ['Namaz kılıyor musun', 'Apakah kamu salat'],
  ['Kur’an okur musun', 'Apakah kamu membaca Al-Qur\u2019an'],
  ['Ramazanda oruç tutar mısın', 'Apakah kamu berpuasa saat Ramadan'],
  ['Helal hassasiyetin var mı', 'Apakah kamu memperhatikan halal'],
  ['Sigara kullanıyor musun', 'Apakah kamu merokok'],
  ['Alkol kullanıyor musun', 'Apakah kamu minum alkohol'],
  ['Kedi sever misin', 'Apakah kamu suka kucing'],
  ['Köpek sever misin', 'Apakah kamu suka anjing'],
  ['Evde hayvan besler misin', 'Apakah kamu memelihara hewan di rumah'],
  ['Yemek yapmayı sever misin', 'Apakah kamu suka memasak'],
  ['En sevdiğin yemek ne', 'Apa makanan favoritmu'],
  ['Türk yemeklerini sever misin', 'Apakah kamu suka makanan Turki'],
  ['Endonezya yemeklerini severim', 'Aku suka makanan Indonesia'],
  ['En sevdiğin renk ne', 'Apa warna favoritmu'],
  ['En sevdiğin film ne', 'Apa film favoritmu'],
  ['Dizi izler misin', 'Apakah kamu menonton serial'],
  ['Müzik dinler misin', 'Apakah kamu mendengarkan musik'],
  ['En sevdiğin şarkıcı kim', 'Siapa penyanyi favoritmu'],
  ['Spor yapar mısın', 'Apakah kamu berolahraga'],
  ['Hangi sporları seversin', 'Olahraga apa yang kamu suka'],
  ['Kitap okur musun', 'Apakah kamu suka membaca buku'],
  ['Hangi kitapları seversin', 'Buku seperti apa yang kamu suka'],
  ['Seyahat etmeyi sever misin', 'Apakah kamu suka bepergian'],
  ['Hangi ülkelere gitmek istersin', 'Negara mana yang ingin kamu kunjungi'],
  ['Türkiye\u2019ye hiç geldin mi', 'Apakah kamu pernah ke Turki'],
  ['Endonezya\u2019ya hiç gittin mi', 'Apakah kamu pernah ke Indonesia'],
  ['Daha önce Türkiye\u2019ye geldin mi', 'Apakah kamu pernah ke Turki'],
  ['Daha önce Endonezya\u2019ya geldin mi', 'Apakah kamu pernah ke Indonesia'],
  ['Orası soğuk mu', 'Di sana dingin'],
  ['Orası sıcak mı', 'Di sana panas'],
  ['Dil biliyor musun', 'Apakah kamu bisa bahasa lain'],
  ['Türkçe biliyor musun', 'Apakah kamu bisa bahasa Turki'],
  ['Endonezce biliyor musun', 'Apakah kamu bisa bahasa Indonesia'],
  ['İngilizce biliyor musun', 'Apakah kamu bisa bahasa Inggris'],
  ['Hangi dilleri konuşuyorsun', 'Bahasa apa saja yang kamu kuasai'],
  ['Günlük hayatın nasıl geçiyor', 'Bagaimana keseharianmu'],
  ['Bugün günün nasıl geçti', 'Bagaimana harimu hari ini'],
  ['Şu an ne yapıyorsun', 'Kamu sedang apa sekarang'],
  ['Müsait misin', 'Kamu sempat'],
  ['Konuşabilir miyiz', 'Boleh kita ngobrol'],
  ['Sesli konuşmak ister misin', 'Apakah kamu ingin teleponan'],
  ['Video görüşme ister misin', 'Apakah kamu ingin video call'],
  ['Yazışmayı mı tercih edersin', 'Apakah kamu lebih suka chat'],
  ['Aile değerleri senin için önemli mi', 'Apakah nilai keluarga penting bagimu'],
  ['Eşinle görev paylaşımı hakkında ne düşünüyorsun', 'Apa pendapatmu tentang berbagi tugas dengan pasangan'],
  ['Çalışan bir eş ister misin', 'Apakah kamu ingin pasangan yang bekerja'],
  ['Ev hanımı olmak ister misin', 'Apakah kamu ingin menjadi ibu rumah tangga'],
  ['Çocuk sahibi olmak ister misin', 'Apakah kamu ingin punya anak'],
  ['Kaç çocuk istersin', 'Berapa anak yang kamu inginkan'],
  ['Ailelerimiz tanışsın mı', 'Apakah keluarga kita perlu saling kenal'],
  ['Ailen evliliğe sıcak bakar mı', 'Apakah keluargamu mendukung pernikahan'],
  ['Türkiye\u2019de yaşamak ister misin', 'Apakah kamu ingin tinggal di Turki'],
  ['Endonezya\u2019da yaşamak ister misin', 'Apakah kamu ingin tinggal di Indonesia'],
  ['Uzak mesafe ilişkisi yapabilir misin', 'Apakah kamu bisa menjalani hubungan jarak jauh'],
  ['Birbirimizi daha iyi tanımak isterim', 'Aku ingin mengenalmu lebih baik'],
  ['Sana saygı duyuyorum', 'Aku menghormatimu'],
  ['Dürüstlük benim için önemli', 'Kejujuran penting bagiku'],
  ['Güven benim için çok önemli', 'Kepercayaan sangat penting bagiku'],
  ['Sınırlarına saygı duyarım', 'Aku menghargai batasanmu'],
  ['İletişim bizim için önemli', 'Komunikasi penting untuk kita'],
  ['Daha ciddi konuşabilir miyiz', 'Boleh kita bicara lebih serius'],
  ['Bu konuda düşünmek isterim', 'Aku ingin memikirkan hal ini'],
  ['Bunu konuşmak için erken olabilir', 'Mungkin terlalu cepat untuk membahas ini'],
  ['Seni tanıdığıma memnun oldum', 'Senang berkenalan denganmu'],
  ['Ben de memnun oldum', 'Aku juga senang'],
  ['Yarın konuşalım mı', 'Kita ngobrol besok ya'],
  ['İyi geceler', 'Selamat malam'],
  ['İyi günler', 'Selamat siang'],
  ['Günaydın', 'Selamat pagi'],
  ['İyi akşamlar', 'Selamat malam'],
  ['İyi uykular', 'Selamat tidur'],
  ['Görüşürüz', 'Sampai jumpa'],
  ['Kendine iyi bak', 'Jaga diri ya'],
  ['Hoşça kal', 'Hati-hati ya'],
  ['Kolay gelsin', 'Semoga lancar ya'],
  ['Teşekkür ederim', 'Terima kasih'],
  ['Rica ederim', 'Sama-sama'],
  ['Özür dilerim', 'Maaf'],
  ['Sorun değil', 'Tidak apa-apa'],
  ['Anladım', 'Aku mengerti'],
  ['Anlamadım', 'Aku tidak mengerti'],
  ['Tekrar eder misin', 'Bisa ulangi'],
  ['Daha yavaş yazar mısın', 'Bisa mengetik lebih pelan'],
  ['Ne demek istedin', 'Maksudmu apa'],
  ['Bunu çok sevdim', 'Aku sangat suka ini'],
  ['Bu çok güzel', 'Ini sangat bagus'],
  ['Bugün hava nasıl', 'Bagaimana cuaca hari ini'],
  ['Nerede çalışıyorsun', 'Di mana kamu bekerja'],
  ['Kaç yıldır çalışıyorsun', 'Sudah berapa tahun kamu bekerja'],
  ['Hangi bölüm mezunusun', 'Kamu lulus jurusan apa'],
  ['Üniversite okudun mu', 'Apakah kamu kuliah'],
  ['Kendini nasıl tanımlarsın', 'Bagaimana kamu menggambarkan dirimu'],
  ['Karakterin nasıldır', 'Seperti apa karaktermu'],
  ['Sakin misin', 'Apakah kamu orang yang tenang'],
  ['Kıskanç mısın', 'Apakah kamu pencemburu'],
  ['Sabırlı mısın', 'Apakah kamu penyabar'],
  ['Öfkelendiğinde ne yaparsın', 'Apa yang kamu lakukan saat marah'],
  ['Tartışma olursa nasıl çözersin', 'Bagaimana kamu menyelesaikan konflik'],
  ['Ailenle ilişkin nasıl', 'Bagaimana hubunganmu dengan keluargamu'],
  ['Arkadaşlarınla vakit geçirir misin', 'Apakah kamu sering menghabiskan waktu dengan teman'],
  ['Hafta sonu planların neler', 'Apa rencanamu di akhir pekan'],
  ['Doğayı sever misin', 'Apakah kamu suka alam'],
  ['Denizi sever misin', 'Apakah kamu suka laut'],
  ['Dağı sever misin', 'Apakah kamu suka gunung'],
  ['Kahve mi çay mı', 'Kopi atau teh'],
  ['Tatlı sever misin', 'Apakah kamu suka makanan manis'],
  ['Baharatlı sever misin', 'Apakah kamu suka pedas'],
  ['En sevdiğin mevsim hangisi', 'Musim favoritmu yang mana'],
  ['Bugün konuşmak iyi geldi', 'Ngobrol hari ini enak sekali'],
  ['Seninle konuşmak hoş', 'Senang ngobrol denganmu'],
  ['Ben de aynı şeyi düşünüyorum', 'Aku juga berpikir begitu'],
  ['Farklı düşünüyorum ama saygı duyuyorum', 'Aku berbeda pendapat tapi aku menghargainya'],
  ['Sence uyumlu muyuz', 'Menurutmu kita cocok tidak'],
  ['Bu eşleşme için teşekkür ederim', 'Terima kasih untuk kecocokan ini'],
  ['Zaman ayırdığın için teşekkür ederim', 'Terima kasih sudah meluangkan waktu'],
  ['İnşallah hayırlısı olur', 'Semoga yang terbaik'],
  ['Allah\u2019a emanet ol', 'Semoga selalu dalam lindungan Allah'],

  // --- Ready wedding-stage questions (TR<->ID) ---
  ['Bu platformda ciddi evlilik niyetiyle misin', 'Apakah kamu di platform ini dengan niat menikah serius'],
  ['Evlilik için zaman planın nasıl', 'Bagaimana rencana waktumu untuk menikah'],
  ['Evlilikte senin için en önemli 3 değer nedir', 'Apa 3 nilai terpenting bagimu dalam pernikahan'],
  ['Hayatında olmazsa olmazların neler', 'Apa hal yang paling tidak bisa kamu kompromikan dalam hidup'],
  ['Bir ilişkide seni en çok mutlu eden şey nedir', 'Apa yang paling membuatmu bahagia dalam sebuah hubungan'],
  ['Bir ilişkide seni en çok zorlayan şey nedir', 'Apa yang paling menantang bagimu dalam sebuah hubungan'],
  ['Kendini 3 kelimeyle anlatır mısın', 'Coba gambarkan dirimu dengan 3 kata'],
  ['Günlük rutinin nasıl', 'Seperti apa rutinitas harianmu'],
  ['Sakin misin yoksa hareketli mi', 'Kamu tipe yang tenang atau aktif'],
  ['Stresliyken ne yaparsın', 'Apa yang kamu lakukan saat stres'],

  ['Ailen evliliğe nasıl bakıyor', 'Bagaimana tanggapan keluargamu tentang pernikahan ini'],
  ['Ailenin onayı senin için ne kadar önemli', 'Seberapa penting persetujuan keluarga bagimu'],
  ['Evlilikte ailelerin rolü sence nasıl olmalı', 'Menurutmu bagaimana peran keluarga dalam pernikahan'],
  ['Aileler tanışması ne zaman uygun olur', 'Kapan waktu yang tepat untuk keluarga saling kenal'],
  ['Evlilikte büyüklerle aynı evde yaşamak ister misin', 'Apakah kamu ingin tinggal satu rumah dengan orang tua setelah menikah'],
  ['Aile ziyaretleri ne sıklıkla olmalı', 'Seberapa sering kunjungan keluarga sebaiknya dilakukan'],
  ['Düğün ve nikahı nasıl hayal ediyorsun', 'Seperti apa kamu membayangkan akad dan pesta pernikahan'],
  ['Sade bir nikah mı büyük bir düğün mü istersin', 'Kamu lebih ingin akad sederhana atau pesta besar'],
  ['İki ülkede de tören yapılması senin için gerekli mi', 'Apakah penting bagimu mengadakan acara di kedua negara'],
  ['Mehir hakkında düşüncen nedir', 'Apa pendapatmu tentang mahar'],
  ['Düğün masrafları nasıl paylaşılmalı', 'Menurutmu biaya pernikahan sebaiknya dibagi bagaimana'],
  ['Nikah sonrası balayını nerede yapmak istersin', 'Setelah menikah kamu ingin bulan madu di mana'],

  ['Dini hayatında ne kadar öncelikli', 'Seberapa penting agama dalam hidupmu'],
  ['Namaz konusunda hassasiyetin var mı', 'Apakah kamu punya komitmen khusus tentang salat'],
  ['Evlilikte dini uyum senin için şart mı', 'Apakah kesesuaian dalam hal agama itu wajib bagimu'],
  ['Çocuklarımızın dini eğitimi hakkında ne düşünüyorsun', 'Apa pendapatmu tentang pendidikan agama untuk anak kita'],
  ['Başörtüsü tesettür gibi konularda hassasiyetin var mı', 'Apakah kamu punya preferensi tentang hijab atau berpakaian tertutup'],

  ['Türkçe öğrenmeye istekli misin', 'Apakah kamu bersedia belajar bahasa Turki'],
  ['Endonezce öğrenmeye istekli misin', 'Apakah kamu bersedia belajar bahasa Indonesia'],
  ['Günlük iletişimde hangi dili kullanmak istersin', 'Dalam komunikasi harian kamu ingin pakai bahasa apa'],
  ['Yanlış anlaşılınca nasıl çözmeyi seversin', 'Kalau ada salah paham kamu biasanya menyelesaikannya bagaimana'],
  ['Tartışma olunca hemen konuşmak mı yoksa sakinleşmek mi', 'Saat konflik kamu lebih suka langsung bicara atau menenangkan diri dulu'],
  ['Günde kaç kez mesajlaşmak senin için ideal', 'Berapa kali chat per hari yang ideal bagimu'],
  ['Görüntülü konuşma senin için önemli mi', 'Apakah video call penting bagimu'],

  ['Evlendikten sonra nerede yaşamayı düşünüyorsun', 'Setelah menikah kamu ingin tinggal di mana'],
  ['Türkiye’de yaşamak senin için uygun mu', 'Apakah tinggal di Turki cocok untukmu'],
  ['Endonezya’da yaşamak senin için uygun mu', 'Apakah tinggal di Indonesia cocok untukmu'],
  ['Uzun vadede hangi ülkede yaşamak istersin', 'Dalam jangka panjang kamu ingin tinggal di negara mana'],
  ['İki ülke arasında gidip gelme fikrine nasıl bakıyorsun', 'Bagaimana menurutmu tentang bolak-balik antara dua negara'],
  ['Şehir mi daha uygun köy mü', 'Kamu lebih cocok tinggal di kota atau di desa'],
  ['Aile yanında mı ayrı evde mi yaşamak istersin', 'Kamu ingin tinggal bersama keluarga atau rumah terpisah'],
  ['Evlilik sonrası çalışma planın nedir', 'Apa rencana kerjamu setelah menikah'],
  ['Eşinin ülkesine taşınmak için en büyük endişen ne olur', 'Apa kekhawatiran terbesarmu jika pindah ke negara pasangan'],

  ['İlk yüz yüze görüşmeyi ne zaman planlayalım', 'Kapan kita rencanakan pertemuan tatap muka pertama'],
  ['Görüşme için hangi şehir daha uygun', 'Kota mana yang lebih cocok untuk bertemu'],
  ['Vize süreçleri hakkında bilgin var mı', 'Apakah kamu tahu tentang proses visa'],
  ['Pasaport vize gibi konularda planın var mı', 'Apakah kamu sudah punya rencana soal paspor dan visa'],
  ['Uçuş masraflarını nasıl planlayalım', 'Bagaimana kita merencanakan biaya penerbangan'],
  ['Ailelerin buluşması için hangi ülke daha kolay', 'Negara mana yang lebih mudah untuk pertemuan keluarga'],
  ['Uzun mesafe ilişkisinde en zor kısım sence ne', 'Menurutmu apa bagian tersulit dari hubungan jarak jauh'],
  ['Uzak mesafede güveni nasıl koruruz', 'Bagaimana kita menjaga kepercayaan dalam jarak jauh'],
  ['Ne sıklıkla yüz yüze görüşmek istersin', 'Seberapa sering kamu ingin bertemu langsung'],

  ['Evlilik sonrası bütçeyi nasıl yönetelim', 'Setelah menikah bagaimana kita mengelola keuangan'],
  ['Ortak hesap mı ayrı hesap mı', 'Lebih cocok rekening bersama atau terpisah'],
  ['Aileye maddi destek konusunda sınırın var mı', 'Apakah kamu punya batasan soal membantu keluarga secara finansial'],
  ['Tasarruf mu yoksa konfor mu daha öncelikli', 'Mana yang lebih prioritas bagimu, menabung atau kenyamanan'],
  ['Borç kredi gibi konularda yaklaşımın nasıl', 'Bagaimana sikapmu soal utang dan kredit'],
  ['Eşinin çalışmasını ister misin', 'Apakah kamu ingin pasanganmu bekerja'],
  ['Evlilikte maddi şeffaflık senin için şart mı', 'Apakah transparansi finansial itu wajib bagimu dalam pernikahan'],

  ['Ev işlerinde iş bölümü nasıl olmalı', 'Bagaimana pembagian tugas rumah tangga seharusnya'],
  ['Temizlik düzen konusunda nasılsın', 'Seperti apa kamu soal kebersihan dan kerapian'],
  ['Misafir ağırlamayı sever misin', 'Apakah kamu suka menerima tamu'],
  ['Evde yalnız zamana ihtiyaç duyar mısın', 'Apakah kamu butuh waktu sendiri di rumah'],
  ['Sosyal medya kullanımında sınırın var mı', 'Apakah kamu punya batasan dalam penggunaan media sosial'],

  ['Çocuk sahibi olmak istiyor musun', 'Apakah kamu ingin punya anak'],
  ['Çocuklarımız hangi dili ana dil yapsın', 'Bahasa apa yang kamu ingin jadi bahasa utama anak kita'],
  ['Çocuk eğitimi konusunda yaklaşımın nasıl', 'Bagaimana pendekatanmu tentang pendidikan anak'],
  ['Çocuklara ekran süresi konusunda ne düşünüyorsun', 'Apa pendapatmu tentang batas waktu layar untuk anak'],
  ['Çocuklarımızın iki kültürü de öğrenmesini ister misin', 'Apakah kamu ingin anak kita mengenal dua budaya sekaligus'],

  ['Kültürel farklılıklar seni endişelendiriyor mu', 'Apakah perbedaan budaya membuatmu khawatir'],
  ['Bayramları ve özel günleri nasıl kutlamayı seversin', 'Bagaimana kamu suka merayakan hari raya dan hari spesial'],
  ['Baharatlı yemekler senin için sorun olur mu', 'Apakah makanan pedas akan menjadi masalah bagimu'],
  ['Gelenek ve modern yaşam arasında dengeyi nasıl kurarsın', 'Bagaimana kamu menyeimbangkan tradisi dan kehidupan modern'],

  ['Özel alan mahremiyet senin için önemli mi', 'Apakah privasi itu penting bagimu'],
  ['Telefon şifre paylaşma konusunda ne düşünüyorsun', 'Apa pendapatmu tentang berbagi sandi ponsel'],
  ['Eşin karşı cins arkadaşlarıyla görüşebilir mi', 'Apakah pasangan boleh berteman dengan lawan jenis'],
  ['Telefon mesaj kontrolü sence doğru mu', 'Menurutmu apakah memeriksa ponsel pasangan itu benar'],

  ['Evlilikte sevgi dilin nedir', 'Apa bahasa cintamu dalam hubungan'],
  ['Evlilikte ortak hedeflerimiz ne olsun istersin', 'Target bersama apa yang kamu ingin kita punya setelah menikah'],
  ['Evlilikte en büyük korkun nedir', 'Apa ketakutan terbesarmu tentang pernikahan'],
  ['Evlilikte en büyük umudun nedir', 'Apa harapan terbesarmu tentang pernikahan'],
];

const TR_TO_ID = new Map();
const ID_TO_TR = new Map();

for (const [tr, id] of PAIRS) {
  if (tr && id) {
    TR_TO_ID.set(norm(tr), id);
    ID_TO_TR.set(norm(id), tr);
  }
}

export function phrasebookTranslate(text, targetLang) {
  const key = norm(text);
  if (!key) return '';

  if (targetLang === 'id') {
    return TR_TO_ID.get(key) || '';
  }
  if (targetLang === 'tr') {
    return ID_TO_TR.get(key) || '';
  }

  return '';
}

export function phrasebookCount() {
  return TR_TO_ID.size;
}
